export const products = [
    { id: 1,
     productName: 'Mango', 
     price: 160, 
     productImg: 'https://s3-alpha-sig.figma.com/img/17d8/db7f/3d627d5dff7a21f5589732970e0ecc60?Expires=1678665600&Signature=Vsqr177Bj3qp~WZz-ba2YGMvGJfghd0gNIIb~BFq70obVwf1gSmuPaGzJaIGzmirjWi0RtMEYqMiXyAGoCTTYTGVXuLNBfDjs5c20gtJ4TPFhZOtdEvOnZgkr73DL9F1za0ZYO-TS-MuvT86rlPFdRehDN~B620oH2PfIs5BRordcgQtSJ6qIy6-8zs3C2TEQCz1zyQWf9BRd4uLLRcnmER3OH2TvV-KBS5gcw4y5oUbAoxS9jkoMm0LQ9wjQv9S-SSebDvDGPeKbgQ0WPNVMAsWlImq1tBpXgLiYUiA0FWZcsxrxMZACiG39bbGY~3g5ad9kgbO8HzVd~C4i5Z6ag__&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4', 
     description: 'A mango is a sweet tropical fruit, and its also the name of the trees on which the fruit grows.', 
      },
     { id: 2,
     productName: 'Strawberry', 
     price: 310, 
     productImg: 'https://images.indianexpress.com/2019/11/strawberries_759.jpg', 
     description: 'A strawberry is both a low-growing, flowering plant and also the name of the fruit that it produces', 
      },
     { id: 3,
     productName: 'Guava', 
     price: 110,
      productImg: 'https://insanelygoodrecipes.com/wp-content/uploads/2020/05/Guava.png', 
     description: 'The fruits are round to pear-shaped and measure up to 7.6 cm in diameter;', 
      },
     { id: 4,
     productName: 'Pomegranate', 
     price: 150, 
     productImg: 'https://grocimart.com/files/images/pomegranate-anaar_15971407280.jpg', 
     description: 'The pomegranate plant is a large shrub or small tree that has smooth, evergreen leaves and showy orange to red flowers', 
     },
     { id: 5,
     productName: 'Pineapple', 
     price: 210,
      productImg: 'https://media.meer.com/attachments/b834149acebea59752e51af94ded73009aff72b6/store/fill/1090/613/61b68a4bf7897b5e646e97753a8dc15a020992e571f4d42a9461f72dcd6f/Pineapple-the-superfood.jpg', 
     description: 'A pineapple is a large oval fruit that grows in hot countries. It is sweet, juicy, and yellow inside, and it has a thick brownish skin.', 
     },
     { id: 6,
     productName: 'Grapes', 
     price: 180, 
     productImg: 'https://i.ndtvimg.com/i/2015-09/grapes_625x350_61443376353.jpg', 
     description: ' Grapes are a type of fruit that grow in clusters of 15 to 300, and can be crimson, black, dark blue, yellow, green, orange, and pink.', 
     },
     { id: 7,
     productName: 'Pears', 
     price: 60, 
     productImg: 'https://images.healthshots.com/healthshots/en/uploads/2022/03/10150922/pears.jpg', 
     description: 'A pear is a sweet, juicy fruit which is narrow near its stalk, and wider and rounded at the bottom.', 
      },
     { id: 8,
     productName: 'Litchi', 
     price: 80, 
     productImg: 'https://www.shutterstock.com/image-photo/front-view-fresh-ripe-lychee-260nw-1896674947.jpg', 
     description: 'The fruits are similar to longan, with the edible part being the translucent aril, which are juicy and sweet to sour in taste', 
      },
     { id: 9,
     productName: 'Apple', 
     price: 110, 
     productImg: 'https://cf.shopee.ph/file/4989d4e12cf751e7d0332914777cf005', 
     description: 'The apple is one of the pome (fleshy) fruits. Apples at harvest vary widely in size, shape, colour', 
     },
     { id: 10,
     productName: 'Orange', 
     price: 150, 
     productImg: 'https://i.ndtvimg.com/i/2018-04/orange_620x350_41522922129.jpg', 
     description: 'a round usually sweet juicy fruit with a yellowish to reddish orange rind.', 
     },
     { id: 11,
     productName: 'Watermelon', 
     price: 100,
      productImg: 'https://blog-images-1.pharmeasy.in/2020/08/28152823/shutterstock_583745164-1.jpg', 
     description: ' a large oblong or roundish fruit with a hard green or white rind often striped or variegated, a sweet watery pink, yellowish, or red pulp, and usually many seeds.', 
     },
     { id: 12,
     productName: 'Coconut', 
     price: 50, 
     productImg: 'https://media.npr.org/assets/img/2011/08/15/coconut-water-6f51be99d73fb9aacd1358747aea2de85aa4d2ff.jpg', 
     description: 'Coconut is the fruit of a tropical palm plant. It has a hard shell, edible white flesh and clear liquid', 
      },
     { id: 13,
     productName: 'Lemmon', 
     price: 10, 
     productImg: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXYtXnrGpzC51dtrKar6MZSflJI4ZEJatK1g&usqp=CAU', 
     description: 'The lemon fruit is an ellipsoid berry surrounded by a green rind, which ripens to yellow, protecting soft yellow segmented pulp', 
      }

];

export default products;